micronaut:
  application:
    name: blogger
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"
  security:
    enabled: true
    intercept-url-map:
      - pattern: /**
        access:
          - isAnonymous()
    oauth2:
      enabled: true
      clients:
        google:
          client-id: '393123747080-cgu69mq0plfbff1aimheoa52jn32qbuh.apps.googleusercontent.com'
          client-secret: 'jxQaD9Y_KYH8G9mk-7obAxB8'
          openid:
            issuer: 'https://accounts.google.com'
    token:
      jwt:
        enabled: true
        cookie:
          enabled: true
        signatures:
          secret:
            generator:
              secret: 48e883bd326a4df8bbccf58e1123029a
    endpoints:
      logout:
        enabled: true
        get-allowed: true
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:4200
endpoints:
  stop:
    enabled: false
    sensitive: false
  beans:
    enabled: false
    sensitive: true
  info:
    enabled: false
    sensitive: false
